all:
	gcc mandelbrot-gschmi4.c -o mandelbrot-gschmi4
	gcc mandelcalc-gschmi4.c -o mandelcalc-gschmi4
	gcc mandeldisplay-gschmi4.c -o mandeldisplay-gschmi4

clean:
	rm mandelbrot-gschmi4 mandelcalc-gschmi4 mandeldisplay-gschmi4
